# 旧CCCaster同梱のErkz作成ステージ選択画像。ゲーム側GRPへ置く9枚だけを出力する。
set(stage_asset_root "${CMAKE_BINARY_DIR}/bin/game-assets")
set(stage_asset_manifest "{\n  \"credit\": \"Stage select graphics fix by Erkz, from legacy CCCaster\",\n  \"files\": [")
set(stage_asset_separator "")
foreach(kind IN ITEMS view jp en)
    foreach(stage IN ITEMS 55 57 58)
        set(relative "GRP/BgSelect/stsel_${kind}/chr_stsel_${kind}${stage}.dds")
        set(source "${CMAKE_CURRENT_SOURCE_DIR}/assets/${relative}")
        file(SHA256 "${source}" digest)
        configure_file("${source}" "${stage_asset_root}/${relative}" COPYONLY)
        string(APPEND stage_asset_manifest "${stage_asset_separator}\n    {\"path\": \"${relative}\", \"sha256\": \"${digest}\"}")
        set(stage_asset_separator ",")
    endforeach()
endforeach()
file(WRITE "${stage_asset_root}/files.sha256.json" "${stage_asset_manifest}\n  ]\n}\n")
